version: '3'
services:
  backend:
    container_name: flaskbackend
    image: flaskbackend:v2
    restart: always
    ports:
      - 5000:5000
    depends_on:
      - mongo

  mongo:
    container_name: mongo
    image: mongo:4.2.0
    ports:
      - 1048:27017